//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace OnlineNewspaperDistribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }

        [Display(Name = "User Name : ")]
        [Required(ErrorMessage = "User Name is required.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter User Name.")]
        public string UserName { get; set; }

        [Display(Name = "EmailId : ")]
        [Required(ErrorMessage = "EmailId is required.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter EmailId address.")]
        public string EmailId { get; set; }

        [Display(Name = "Feedback : ")]
        [Required(ErrorMessage = "Feedback1 is required.")]
        public string Feedback1 { get; set; }
    }
}
