//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace OnlineNewspaperDistribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewspaperMaster
    {
        [Display(Name = "Newspaper Id")]
        public int NewspaperId { get; set; }

        [Display(Name = "Newspaper Name")]
        public string NewspaperName { get; set; }

        [Display(Name = "Is Active")]
        public bool IsActive { get; set; }

        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Display(Name = "Vendor Id")]
        public Nullable<int> VendorId { get; set; }

        [Display(Name = "Monthly Price")]
        public Nullable<decimal> MonthlyPrice { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDateTime { get; set; }
    }
}
