//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNewspaperDistribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribed
    {
        public int SubscriptionId { get; set; }
        public int UserId { get; set; }
        public int NewspaperId { get; set; }
        public string NewspaperName { get; set; }
        public bool IsActive { get; set; }
        public decimal Price { get; set; }
        public int VendorId { get; set; }
        public decimal MonthlyPrice { get; set; }
    
        public virtual Subscribed Subscribed1 { get; set; }
        public virtual Subscribed Subscribed2 { get; set; }
    }
}
