//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNewspaperDistribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionDetail
    {
        public int SubscriptionId { get; set; }
        public Nullable<int> NewsPaperId { get; set; }
        public int CustomerId { get; set; }
        public string Plans { get; set; }
        public string Price { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDateTIme { get; set; }
    
        public virtual SubscriptionDetail SubscriptionDetails1 { get; set; }
        public virtual SubscriptionDetail SubscriptionDetail1 { get; set; }
    }
}
