//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace OnlineNewspaperDistribution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [Display(Name = "User Id")]
        public int UserId { get; set; }

        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Display(Name = "EmailId")]
        public string EmailId { get; set; }

        [Display(Name = "Street Name")]
        public string StreetName { get; set; }
        public string UserSalt { get; set; }
        public int UserTypeId { get; set; }
        public string Password { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDateTime { get; set; }
    
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
    }
}
